name: Bug Report
description: Create a bug report
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Description
      description: "Please provide a description and way to reproduce the problem."
      placeholder: |
        Please use Eramba Discussions for questions.

        https://discussions.eramba.org
    validations:
      required: true
  - type: input
    attributes:
      label: Eramba Version
      description: "Eramba version used."
      placeholder: "3.15.0"
    validations:
      required: true
  - type: input
    attributes:
      label: PHP Version
      description: "The php version used, if needed."
      placeholder: "8.0"
    validations:
      required: false
