name: Bug Report
description: Create a bug report
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Description
      description: "Please provide a description and way to reproduce the problem."
      placeholder: |
        Please use Eramba Discussions for questions.

        https://discussions.eramba.org
    validations:
      required: true
  - type: input
    attributes:
      label: Eramba Version
      description: "Eramba version used."
      placeholder: "3.15.0"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. On section Legals
        2. I clicked Add New
        3. I got an error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false
